export const ROCKETS_MODULE_OPTIONS_DEFAULT_SETTINGS_TOKEN =
  'ROCKETS_MODULE_OPTIONS_DEFAULT_SETTINGS_TOKEN';

export const RocketsAuthProvider = Symbol('ROCKETS_AUTH_PROVIDER');

export const USER_METADATA_MODULE_ENTITY_KEY = 'userMetadata';

export const USER_MODULE_USER_ENTITY_KEY = 'user';
export const UserModelService = 'USER_MODULE_USER_SERVICE_KEY';
