export const FIREBASE_TOKEN_VERIFIER_TOKEN = Symbol(
  '__FIREBASE_TOKEN_VERIFIER_TOKEN__',
);

export const FIREBASE_USER_RESOLVER_TOKEN = Symbol(
  '__FIREBASE_USER_RESOLVER_TOKEN__',
);

export const FIREBASE_AUTH_MODULE_OPTIONS_TOKEN = Symbol(
  '__FIREBASE_AUTH_MODULE_OPTIONS_TOKEN__',
);
