name: ci-merge
on:
  push:
    branches: ["main"]
  workflow_dispatch:
    branches: ["main"]
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --immutable

      - name: Debug - Check TypeScript installation
        run: |
          echo "Checking TypeScript installation..."
          yarn tsc --version || echo "TypeScript not found via yarn"
          npx tsc --version || echo "TypeScript not found via npx"
          ls -la node_modules/.bin/ | grep tsc || echo "No tsc in node_modules/.bin"

      - name: Build
        run: yarn build || yarn build:fallback
      - name: Unit tests
        run: yarn test:ci
      - name: Process Test Results
        uses: dorny/test-reporter@v1
        with:
          name: Jest Tests
          path: "junit.xml"
          reporter: jest-junit
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/coverage-final.json
          verbose: true
      - name: Upload coverage to Code Climate
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{ github.workspace }}/coverage/lcov.info:lcov
      - name: Upload coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./coverage/lcov.info
