name: ci-pr-report
on:
  workflow_run:
    workflows: ['ci-pr-test']
    types:
      - completed
jobs:
  test-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Process Test Results
        uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: Jest Tests
          path: 'junit.xml'
          reporter: jest-junit
  coverage-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Download artifacts
        uses: actions/upload-artifact@v4
        with:
          workflow: ci-pr-test.yml
          name: test-results
      - name: Get PR Number
        id: vars
        run: echo ::set-output name=pr_num::$(cat pr_num.txt)
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ${{ github.workspace }}/coverage/coverage-final.json
          override_pr: ${{ steps.vars.outputs.pr_num }}
          verbose: true
      - name: Upload coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ${{ github.workspace }}/coverage/lcov.info
      - name: Upload coverage to Code Climate
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{ github.workspace }}/coverage/lcov.info:lcov
