name: ci-pr-test

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --immutable

      - name: Debug - Check TypeScript installation
        run: |
          echo "Checking TypeScript installation..."
          yarn tsc --version || echo "TypeScript not found via yarn"
          npx tsc --version || echo "TypeScript not found via npx"
          ls -la node_modules/.bin/ | grep tsc || echo "No tsc in node_modules/.bin"

      - name: Build
        run: yarn build || yarn build:fallback
      - name: Linting
        run: yarn lint:all
      - name: Unit tests
        run: yarn test:ci
      - name: Save the PR number in an artifact
        shell: bash
        env:
          PR_NUM: ${{ github.event.number }}
        run: |
          echo $PR_NUM > ./pr_num.txt
      - name: Upload test-results artifact
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: |
            pr_num.txt
            junit.xml
            coverage/lcov.info
            coverage/coverage-final.json
